# SVISSR-Ingestor configuration

# Satellite name. 
# For consistency it is advised to keep either FY-2H, FY-2G, etc in the same 
# format, but otherwise you can put anything
satellite_name: FY-2H

# SDR Settings
radio:
  device: "driver=airspy" # SoapySDR device string
  frequency: 1687500000 # S-VISSR Frequency
  sample_rate: 3000000 # Samplerate. Has to be >= 0.660MSPS
  gain: 40 # SDR Gain, an integer
  biastee: true

# Data director to save the pictures in
data_directory: SVISSR_DATA

# Write demodulated data to svissr.bin (debugging only, ignore otherwise)
write_demod_bin: false
